sonar.projectKey=cohort-9-mern-14608-adnan
sonar.projectName=Notes App
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/jest.setup.ts,**/*.config.js,**/*.config.cjs,**/*.config.ts,**/*.config.mjs,**/*.d.ts,**/react-router-mock.ts,**/package.json,**/package-lock.json,**/tsconfig*.json,**/test-utils/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.coverage.exclusions=backend/src/server.ts
sonar.sourceEncoding=UTF-8
